"""extend_task_workflow_fields

Revision ID: 7024ee49ebcd
Revises: 8f55448fc2d8
Create Date: 2025-12-09 17:39:07.551084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7024ee49ebcd'
down_revision: Union[str, None] = '8f55448fc2d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create enum types first
    workflow_state = sa.Enum('DRAFT', 'PENDING_CLIENT', 'APPROVED', 'DECLINED', 'EXPIRED', name='workflowstate')
    workflow_state.create(op.get_bind(), checkfirst=True)
    
    approval_action = sa.Enum('APPROVED', 'DECLINED', name='approvalaction')
    approval_action.create(op.get_bind(), checkfirst=True)
    
    # Add workflow columns to tasks table
    op.add_column('tasks', sa.Column('workflow_state', sa.Enum('DRAFT', 'PENDING_CLIENT', 'APPROVED', 'DECLINED', 'EXPIRED', name='workflowstate'), nullable=True))
    op.add_column('tasks', sa.Column('approval_required_by', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tasks', sa.Column('approved_by_client_user_id', sa.UUID(as_uuid=False), nullable=True))
    op.add_column('tasks', sa.Column('approval_action', sa.Enum('APPROVED', 'DECLINED', name='approvalaction'), nullable=True))
    op.add_column('tasks', sa.Column('approval_comment', sa.String(length=2000), nullable=True))
    op.add_column('tasks', sa.Column('approval_acted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tasks', sa.Column('proposal_data', sa.JSON(), nullable=True))
    op.create_foreign_key('fk_tasks_approved_by_client_user', 'tasks', 'client_users', ['approved_by_client_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_tasks_approved_by_client_user', 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'proposal_data')
    op.drop_column('tasks', 'approval_acted_at')
    op.drop_column('tasks', 'approval_comment')
    op.drop_column('tasks', 'approval_action')
    op.drop_column('tasks', 'approved_by_client_user_id')
    op.drop_column('tasks', 'approval_required_by')
    op.drop_column('tasks', 'workflow_state')
    
    # Drop enum types
    sa.Enum(name='approvalaction').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='workflowstate').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###

