"""add_client_user_model

Revision ID: 8f55448fc2d8
Revises: b7c8d9e0f1a2
Create Date: 2025-12-09 16:47:20.420848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f55448fc2d8'
down_revision: Union[str, None] = 'b7c8d9e0f1a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_users',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('client_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('mfa_secret', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_users_client_id'), 'client_users', ['client_id'], unique=True)
    op.create_index(op.f('ix_client_users_email'), 'client_users', ['email'], unique=True)
    op.create_index(op.f('ix_client_users_tenant_id'), 'client_users', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_client_users_tenant_id'), table_name='client_users')
    op.drop_index(op.f('ix_client_users_email'), table_name='client_users')
    op.drop_index(op.f('ix_client_users_client_id'), table_name='client_users')
    op.drop_table('client_users')
    # ### end Alembic commands ###

