"""add chat models

Revision ID: e8445e300643
Revises: h3i4j5k6l7m8
Create Date: 2026-02-27 13:00:04.146247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e8445e300643'
down_revision: Union[str, None] = 'h3i4j5k6l7m8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_sessions',
    sa.Column('id', sa.UUID(as_uuid=False).with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('client_id', sa.UUID(as_uuid=False).with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_sessions_client_id'), 'chat_sessions', ['client_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.UUID(as_uuid=False).with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('session_id', sa.UUID(as_uuid=False).with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('client_side_id', sa.String(length=36), nullable=True),
    sa.Column('sender_type', sa.String(length=20), nullable=False),
    sa.Column('sender_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('message_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_side_id')
    )
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.create_table('chat_session_members',
    sa.Column('id', sa.UUID(as_uuid=False).with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('session_id', sa.UUID(as_uuid=False).with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False).with_variant(sa.String(length=36), 'sqlite'), nullable=True),
    sa.Column('client_user_id', sa.UUID(as_uuid=False).with_variant(sa.String(length=36), 'sqlite'), nullable=True),
    sa.Column('user_type', sa.String(length=20), nullable=False),
    sa.Column('last_read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_user_id'], ['client_users.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_session_members_session_id'), 'chat_session_members', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_session_members_session_id'), table_name='chat_session_members')
    op.drop_table('chat_session_members')
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_chat_sessions_client_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    # ### end Alembic commands ###
